events {
    worker_connections 1024;
}

http {
    # Cấu hình Rate Limit:  10 request / 1 giây trên mỗi IP
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    server {
        listen 80;

        location / {
            # Áp dụng rate limit, nếu vượt quá sẽ trả về mã lỗi 429 Too Many Requests
            limit_req zone=api_limit burst=20 nodelay;
            
            # Đẩy request vào container api-wrapper ở port 8000
            proxy_pass http://api-wrapper:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}